name: code_mint_frontend
description: "Code_Mint Frontend"


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.7.2







dependencies:
  flutter:
    sdk: flutter

  
  
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  socket_io_client: ^2.0.3+1
  flutter_code_editor: ^0.3.4
  highlight: ^0.7.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^5.0.0





flutter:

  
  
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  #
  
  
